version: '3'

services:
  flask_api:
    build: .
    restart: always
    env_file:
      - src/core/.env
    command: gunicorn src.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --reload
    ports:
      - "8000:8000"
    networks:
      - api

  database:
    image: postgres:13-alpine3.16
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - database/.env
    volumes:
      - ./database/init_data/:/docker-entrypoint-initdb.d/
      - ./database/data:/var/lib/postgresql/data/
    networks:
      - etl

  redis:
    image: redis:6.2.6
    restart: always
    container_name: redis_cashe
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    networks:
      - api
    depends_on:
      - flask_api

  nginx:
    image: nginx:1.21.6
    restart: always
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    networks:
      - api
    depends_on:
      - flask_api

volumes:
  cache:
    driver: local

networks:
  api:
    driver: bridge