version: '3'

services:
  flask_api:
    build: flask_app
    restart: always
    container_name: flask_app
    volumes:
      - ./flask_app/src:/usr/src/app
    env_file:
      - flask_app/src/project/core/.env
    command: python pywsgi.py
    ports:
      - "5000:5000"
    networks:
      - api
    depends_on:
      - database
      - redis

  database:
    image: postgres:13-alpine3.16
    restart: always
    container_name: postgres
    expose:
      - "5432"
    env_file:
      - database/.env
    volumes:
      - ./database/init_data/:/docker-entrypoint-initdb.d/
      - ./database/data:/var/lib/postgresql/data/
    networks:
      - api

  redis:
    image: redis:6.2.6
    restart: always
    container_name: redis
    expose:
      - "6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    networks:
      - api

volumes:
  cache:
    driver: local

networks:
  api:
    driver: bridge