"""add user auth

Revision ID: 68f91e243c47
Revises: 7b1728e67791
Create Date: 2022-07-13 16:55:06.097391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f91e243c47'
down_revision = '7b1728e67791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hashed', sa.String(length=128), nullable=False),
    sa.Column('auth_token', sa.String(length=64), nullable=True),
    sa.Column('auth_token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_auth_token'), 'users', ['auth_token'], unique=False)
    op.add_column('entries', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'entries', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entries', type_='foreignkey')
    op.drop_column('entries', 'user_id')
    op.drop_index(op.f('ix_users_auth_token'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
